export const ORDER_CREATE_REQUEST = "ORDER_CREATE_REQUEST"
export const ORDER_CREATE_SUCCESS = "ORDER_CREATE_SUCCSSESS"
export const ORDER_CREATE_FAIL = "ORDER_CREATE_FAIL"

export const ORDER_DETAILS_REQUEST = "ORDER_DETAILS_REQUEST"
export const ORDER_DETAILS_SUCCESS = "ORDER_DETAILS_SUCCSSESS"
export const ORDER_DETAILS_FAIL = "ORDER_DETAILS_FAIL"

export const ORDER_PAY_REQUEST = "ORDER_PAY_REQUEST"
export const ORDER_PAY_SUCCESS = "ORDER_PAY_SUCCSSESS"
export const ORDER_PAY_FAIL = "ORDER_PAY_FAIL"
export const ORDER_PAY_RESET = "ORDER_PAY_RESET"

export const ORDER_HISTORY_REQUEST = "ORDER_HISTORY_REQUEST"
export const ORDER_HISTORY_SUCCESS = "ORDER_HISTORY_SUCCSSESS"
export const ORDER_HISTORY_FAIL = "ORDER_HISTORY_FAIL"
export const ORDER_HISTORY_RESET = "ORDER_HISTORY_RESET"
