export const ORDER_CREATE_REQUEST = "ORDER_CREATE_REQUEST"
export const ORDER_CREATE_SUCCESS = "ORDER_CREATE_SUCCESS"
export const ORDER_CREATE_FAIL = "ORDER_CREATE_FAIL"
export const ORDER_CREATE_RESET = "ORDER_CREATE_RESET"

export const ORDER_DETAILS_REQUEST = "ORDER_DETAILS_REQUEST"
export const ORDER_DETAILS_SUCCESS = "ORDER_DETAILS_SUCCESS"
export const ORDER_DETAILS_FAIL = "ORDER_DETAILS_FAIL"

export const ORDER_PAY_REQUEST = "ORDER_PAY_REQUEST"
export const ORDER_PAY_SUCCESS = "ORDER_PAY_SUCCESS"
export const ORDER_PAY_FAIL = "ORDER_PAY_FAIL"
export const ORDER_PAY_RESET = "ORDER_PAY_RESET"

export const ORDER_HISTORY_REQUEST = "ORDER_HISTORY_REQUEST"
export const ORDER_HISTORY_SUCCESS = "ORDER_HISTORY_SUCCESS"
export const ORDER_HISTORY_FAIL = "ORDER_HISTORY_FAIL"
export const ORDER_HISTORY_RESET = "ORDER_HISTORY_RESET"

//admin operation
export const ORDERS_LIST_ALL_REQUEST = "ORDERS_LIST_ALL_REQUEST"
export const ORDERS_LIST_ALL_SUCCESS = "ORDERS_LIST_ALL_SUCCESS"
export const ORDERS_LIST_ALL_FAIL = "ORDERS_LIST_ALL_FAIL"
export const ORDERS_LIST_ALL_RESET = "ORDERS_LIST_ALL_RESET"


//admin operation
export const ORDER_SET_DELIVERD_REQUEST = "ORDER_SET_DELIVERD_REQUEST"
export const ORDER_SET_DELIVERD_SUCCESS = "ORDER_SET_DELIVERD_SUCCESS"
export const ORDER_SET_DELIVERD_FAIL = "ORDER_SET_DELIVERD_FAIL"
export const ORDER_SET_DELIVERD_RESET = "ORDER_SET_DELIVERD_RESET"


