export const PRODUCTS_LIST_REQUEST = 'PRODUCTS_LIST_REQUEST'
export const PRODUCTS_LIST_SUCCESS = 'PRODUCTS_LIST_SUCCESS'
export const PRODUCTS_LIST_FAIL = 'PRODUCTS_LIST_FAIL'

export const PRODUCT_CARD_REQUEST = 'PRODUCT_CARD_REQUEST'
export const PRODUCT_CARD_SUCCESS = 'PRODUCT_CARD_SUCCESS'
export const PRODUCT_CARD_FAIL = 'PRODUCT_CARD_FAIL'