export const PRODUCTS_LIST_REQUEST = 'PRODUCTS_LIST_REQUEST'
export const PRODUCTS_LIST_SUCCESS = 'PRODUCTS_LIST_SUCCESS'
export const PRODUCTS_LIST_FAIL = 'PRODUCTS_LIST_FAIL'

export const PRODUCT_CARD_REQUEST = 'PRODUCT_CARD_REQUEST'
export const PRODUCT_CARD_SUCCESS = 'PRODUCT_CARD_SUCCESS'
export const PRODUCT_CARD_FAIL = 'PRODUCT_CARD_FAIL'

//admin only operation
export const PRODUCT_DELETE_REQUEST = 'PRODUCT_DELETE_REQUEST'
export const PRODUCT_DELETE_SUCCESS = 'PRODUCT_DELETE_SUCCESS'
export const PRODUCT_DELETE_FAIL = 'PRODUCT_DELETE_FAIL'

//admin only operation
export const PRODUCT_CREATE_REQUEST = 'PRODUCT_CREATE_REQUEST'
export const PRODUCT_CREATE_SUCCESS = 'PRODUCT_CREATE_SUCCESS'
export const PRODUCT_CREATE_FAIL = 'PRODUCT_CREATE_FAIL'
export const PRODUCT_CREATE_RESET = 'PRODUCT_CREATE_RESET'

//admin only operation
export const PRODUCT_UPDATE_REQUEST = 'PRODUCT_UPDATE_REQUEST'
export const PRODUCT_UPDATE_SUCCESS = 'PRODUCT_UPDATE_SUCCESS'
export const PRODUCT_UPDATE_FAIL = 'PRODUCT_UPDATE_FAIL'
export const PRODUCT_UPDATE_RESET = 'PRODUCT_UPDATE_RESET'


export const PRODUCT_ADD_REVIEW_REQUEST = 'PRODUCT_ADD_REVIEW_REQUEST'
export const PRODUCT_ADD_REVIEW_SUCCESS = 'PRODUCT_ADD_REVIEW_SUCCESS'
export const PRODUCT_ADD_REVIEW_FAIL = 'PRODUCT_ADD_REVIEW_FAIL'
export const PRODUCT_ADD_REVIEW_RESET = 'PRODUCT_ADD_REVIEW_RESET'