export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL'
export const USER_LOGOUT = 'USER_LOGOUT'

export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST'
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS'
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL'

export const USER_PROFILE_REQUEST = 'USER_PROFILE_REQUEST'
export const USER_PROFILE_SUCCESS = 'USER_PROFILE_SUCCESS'
export const USER_PROFILE_FAIL = 'USER_PROFILE_FAIL'
export const USER_PROFILE_RESET = 'USER_PROFILE_RESET'

export const USER_PROFILE_UPDATE_REQUEST = 'USER_PROFILE_UPDATE_REQUEST'
export const USER_PROFILE_UPDATE_SUCCESS = 'USER_PROFILE_UPDATE_SUCCESS'
export const USER_PROFILE_UPDATE_FAIL = 'USER_PROFILE_UPDATE_FAIL'
export const USER_PROFILE_UPDATE_RESET = 'USER_PROFILE_UPDATE_RESET'

//admin's all users list
export const USER_COMPLETE_LIST_REQUEST = 'USER_COMPLETE_LIST_REQUEST'
export const USER_COMPLETE_LIST_SUCCESS = 'USER_COMPLETE_LIST_SUCCESS'
export const USER_COMPLETE_LIST_FAIL = 'USER_COMPLETE_LIST_FAIL'
export const USER_COMPLETE_LIST_RESET = 'USER_COMPLETE_LIST_RESET'

//admin's delete user
export const USER_DELETE_REQUEST = 'USER_DELETE_REQUEST'
export const USER_DELETE_SUCCESS = 'USER_DELETE_SUCCESS'
export const USER_DELETE_FAIL = 'USER_COMPLETE_LIST_FAIL'

//admin's update user
export const USER_PROFILE_UPDATE_BY_ADMIN_REQUEST = 'USER_PROFILE_UPDATE_BY_ADMIN_REQUEST'
export const USER_PROFILE_UPDATE_BY_ADMIN_SUCCESS = 'USER_PROFILE_UPDATE_BY_ADMIN_SUCCESS'
export const USER_PROFILE_UPDATE_BY_ADMIN_FAIL = 'USER_PROFILE_UPDATE_BY_ADMIN_FAIL'
export const USER_PROFILE_UPDATE_BY_ADMIN_RESET = 'USER_PROFILE_UPDATE_BY_ADMIN_RESET'