const products = [
  {
    _id: '1',
    name: 'The Manipulator',
    image: '/images/manipulator.jpg',
    description: 'Extreme vocal transformer',
    brand: 'Polyverse',
    category: 'plugin',
    price: 149,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: '2',
    name: 'COMET',
    image: '/images/comet.jpg',
    description: 'Lush,versatile reverb',
    brand: 'Polyverse',
    category: 'plugin',
    price: 149,
    countInStock: 7,
    rating: 4.0,
    numReviews: 8,
  },
  {
    _id: '3',
    name: 'INFECTED BUNDLE',
    image: '/images/pluginbundle.jpg',
    description: 'Work with the tools of the Shrooms',
    brand: 'Polyverse VS. Infected Mushrooms ',
    category: 'bundle',
    price: 249,
    countInStock: 5,
    rating: 3,
    numReviews: 12,
  },
  {
    _id: '4',
    name: 'i WISH',
    image: '/images/iWish.jpg',
    description: 'Pitch freezer plug-in',
    brand: 'Sony',
    category: 'Electronics',
    price: 399.99,
    countInStock: 11,
    rating: 5,
    numReviews: 12,
  },
  {
    _id: '5',
    name: 'WIDER',
    image: '/images/wider.jpg',
    description: 'Stereo widener plug-in',
    brand: 'Polyverse',
    category: 'Plugin',
    price: 'FREE',
    countInStock: 7,
    rating: 3.5,
    numReviews: 10,
  },
]

export default products
